services:
  postgres:
    image: postgres:15
    container_name: postgres_estudos
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_estudos:/var/lib/postgresql/data
    networks:
      - rede

  airflow-init:
    image: apache/airflow:2.9.1
    container_name: airflow-init
    entrypoint: ["bash", "-c", "airflow db init && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"]
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres_estudos:5432/airflow
      - AIRFLOW__WEBSERVER__SECRET_KEY=uma_chave_muito_secreta_123
      - AIRFLOW__LOGGING__REMOTE_LOGGING=False
    depends_on:
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags
    networks:
      - rede

  airflow-webserver:
    image: apache/airflow:2.9.1
    container_name: airflow-webserver
    restart: always
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres_estudos:5432/airflow
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
      - AIRFLOW__WEBSERVER__SECRET_KEY=uma_chave_muito_secreta_123
      - AIRFLOW__LOGGING__REMOTE_LOGGING=False
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
    command: webserver
    networks:
      - rede

  airflow-scheduler:
    image: apache/airflow:2.9.1
    container_name: airflow-scheduler
    restart: always
    depends_on:
      - airflow-webserver
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres_estudos:5432/airflow
      - AIRFLOW__WEBSERVER__SECRET_KEY=uma_chave_muito_secreta_123
      - AIRFLOW__LOGGING__REMOTE_LOGGING=False
    volumes:
      - ./dags:/opt/airflow/dags
    command: scheduler
    networks:
      - rede

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:latest
    container_name: dbt
    volumes:
      - ./dbt/gastos_publicos:/usr/app
      - ./.dbt:/root/.dbt
    working_dir: /usr/app
    entrypoint: ["sh", "-c", "sleep infinity"]
    depends_on:
      - postgres
    networks:
      - rede

networks:
  rede:
    driver: bridge
